export const seedRecipes = [
  {
    "id": "themealdb-52961",
    "title": "Budino Di Ricotta",
    "description": "An Italian dessert from TheMealDB.",
    "category": "Dessert",
    "tags": [
      "italian",
      "cake",
      "baking",
      "desert",
      "sweet",
      "alcoholic",
      "calorific"
    ],
    "ingredients": "500g Ricotta\n4 large Eggs\n3 tbs Flour\n250g Sugar\n1 tsp Cinnamon\nGrated Zest of 2 Lemons\n5 tbs Dark Rum\nsprinking Icing Sugar",
    "instructions": "Mash the ricotta and beat well with the egg yolks, stir in the flour, sugar, cinnamon, grated lemon rind and the rum and mix well. You can do this in a food processor. Beat the egg whites until stiff, fold in and pour into a buttered and floured 25cm cake tin. Bake in the oven at 180ºC/160ºC fan/gas 4 for about 40 minutes, or until it is firm.\nServe hot or cold dusted with icing sugar.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/1549542877.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://thehappyfoodie.co.uk/recipes/ricotta-cake-budino-di-ricotta",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52796",
    "title": "Chicken Alfredo Primavera",
    "description": "An Italian chicken from TheMealDB.",
    "category": "Chicken",
    "tags": [
      "italian",
      "pasta",
      "meat",
      "dairy"
    ],
    "ingredients": "2 tablespoons Butter\n3 tablespoons Olive Oil\n5 boneless Chicken\n1 teaspoon Salt\n1 cut into 1/2-inch cubes Squash\n1 Head chopped Broccoli\n8-ounce sliced mushrooms\n1 red Pepper\n1 chopped onion\n3 cloves garlic\n1/2 teaspoon red pepper flakes\n1/2 cup white wine\n1/2 cup milk\n1/2 cup heavy cream\n1 cup grated Parmesan cheese\n16 ounces bowtie pasta\npinch Salt\npinch Pepper\nchopped Parsley",
    "instructions": "Heat 1 tablespoon of butter and 2 tablespoons of olive oil in a large skillet over medium-high heat. Season both sides of each chicken breast with seasoned salt and a pinch of pepper. Add the chicken to the skillet and cook for 5-7 minutes on each side, or until cooked through.  While the chicken is cooking, bring a large pot of water to a boil. Season the boiling water with a few generous pinches of kosher salt. Add the pasta and give it a stir. Cook, stirring occasionally, until al dente, about 12 minutes. Reserve 1/2 cup of  pasta water before draining the pasta.  Remove the chicken from the pan and transfer it to a cutting board; allow it to rest. Turn the heat down to medium and dd the remaining 1 tablespoon of butter and olive oil to the same pan you used to cook the chicken. Add the veggies (minus the garlic) and red pepper flakes to the pan and stir to coat with the oil and butter (refrain from seasoning with salt until the veggies are finished browning). Cook, stirring often, until the veggies are tender, about 5 minutes. Add the garlic and a generous pinch of salt and pepper to the pan and cook for 1 minute.  Deglaze the pan with the white wine. Continue to cook until the wine has reduced by half, about 3 minutes. Stir in the milk, heavy cream, and reserved pasta water. Bring the mixture to a gentle boil and allow to simmer and reduce for 2-3 minutes. Turn off the heat and add the Parmesan cheese and cooked pasta. Season with salt and pepper to taste. Garnish with Parmesan cheese and chopped parsley, if desired.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://www.themealdb.com/meal/52796",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52839",
    "title": "Chilli prawn linguine",
    "description": "An Italian pasta from TheMealDB.",
    "category": "Pasta",
    "tags": [
      "italian"
    ],
    "ingredients": "280g Linguine Pasta\n200g Sugar Snap Peas\n2 tblsp Olive Oil\n2 cloves chopped Garlic Clove\n1 large Red Chilli\n24 Skinned King Prawns\n12 Cherry Tomatoes\nHandful Basil Leaves\nLeaves Lettuce\nto serve Bread\n2 tbsp Fromage Frais\nGrated Zest of 2 Lime\n2 tsp Caster Sugar",
    "instructions": "Mix the dressing ingredients in a small bowl and season with salt and pepper. Set aside.\nCook the pasta according to the packet instructions. Add the sugar snap peas for the last minute or so of cooking time.\nMeanwhile, heat the oil in a wok or large frying pan, toss in the garlic and chilli and cook over a fairly gentle heat for about 30 seconds without letting the garlic brown. Tip in the prawns and cook over a high heat, stirring frequently, for about 3 minutes until they turn pink.\nAdd the tomatoes and cook, stirring occasionally, for 3 minutes until they just start to soften. Drain the pasta and sugar snaps well, then toss into the prawn mixture. Tear in the basil leaves, stir, and season with salt and pepper.\nServe with salad leaves drizzled with the lime dressing, and warm crusty bread.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/usywpp1511189717.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://www.bbcgoodfood.com/recipes/1269/chilli-prawn-linguine",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-53064",
    "title": "Fettuccine Alfredo",
    "description": "An Italian pasta from TheMealDB.",
    "category": "Pasta",
    "tags": [
      "italian"
    ],
    "ingredients": "1 lb Fettuccine\n1/2 cup Heavy Cream\n1/2 cup Butter\n1/2 cup Parmesan\n2 tbsp Parsley\nBlack Pepper",
    "instructions": "Cook pasta according to package instructions in a large pot of boiling water and salt. Add heavy cream and butter to a large skillet over medium heat until the cream bubbles and the butter melts. Whisk in parmesan and add seasoning (salt and black pepper). Let the sauce thicken slightly and then add the pasta and toss until coated in sauce. Garnish with parsley, and it's ready.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/0jv5gx1661040802.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://www.delish.com/cooking/recipe-ideas/a55312/best-homemade-fettuccine-alfredo-recipe/",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52835",
    "title": "Fettucine alfredo",
    "description": "An Italian pasta from TheMealDB.",
    "category": "Pasta",
    "tags": [
      "italian"
    ],
    "ingredients": "227g Clotted Cream\n25g Butter\n1 tsp Corn Flour\n100g Parmesan Cheese\nGrated Nutmeg\n250g Fettuccine\nChopped Parsley",
    "instructions": "In a medium saucepan, stir the clotted cream, butter and cornflour over a low-ish heat and bring to a low simmer. Turn off the heat and keep warm.\nMeanwhile, put the cheese and nutmeg in a small bowl and add a good grinding of black pepper, then stir everything together (don’t add any salt at this stage).\nPut the pasta in another pan with 2 tsp salt, pour over some boiling water and cook following pack instructions (usually 3-4 mins). When cooked, scoop some of the cooking water into a heatproof jug or mug and drain the pasta, but not too thoroughly.\nAdd the pasta to the pan with the clotted cream mixture, then sprinkle over the cheese and gently fold everything together over a low heat using a rubber spatula. When combined, splash in 3 tbsp of the cooking water. At first, the pasta will look wet and sloppy: keep stirring until the water is absorbed and the sauce is glossy. Check the seasoning before transferring to heated bowls. Sprinkle over some chives or parsley, then serve immediately.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/uquqtu1511178042.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://www.bbcgoodfood.com/recipes/fettucine-alfredo",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52844",
    "title": "Lasagne",
    "description": "An Italian pasta from TheMealDB.",
    "category": "Pasta",
    "tags": [
      "italian"
    ],
    "ingredients": "1 tblsp Olive Oil\n2 Bacon\n1 finely chopped Onion\n1 Stick Celery\n1 medium Carrots\n2 cloves chopped Garlic\n500g Minced Beef\n1 tbls Tomato Puree\n800g Chopped Tomatoes\n1 tblsp Honey\n500g Lasagne Sheets\n400ml Creme Fraiche\n125g Mozzarella Balls\n50g Parmesan Cheese\nTopping Basil Leaves",
    "instructions": "Heat the oil in a large saucepan. Use kitchen scissors to snip the bacon into small pieces, or use a sharp knife to chop it on a chopping board. Add the bacon to the pan and cook for just a few mins until starting to turn golden. Add the onion, celery and carrot, and cook over a medium heat for 5 mins, stirring occasionally, until softened.\nAdd the garlic and cook for 1 min, then tip in the mince and cook, stirring and breaking it up with a wooden spoon, for about 6 mins until browned all over.\nStir in the tomato purée and cook for 1 min, mixing in well with the beef and vegetables. Tip in the chopped tomatoes. Fill each can half full with water to rinse out any tomatoes left in the can, and add to the pan. Add the honey and season to taste. Simmer for 20 mins.\nHeat oven to 200C/180C fan/gas 6. To assemble the lasagne, ladle a little of the ragu sauce into the bottom of the roasting tin or casserole dish, spreading the sauce all over the base. Place 2 sheets of lasagne on top of the sauce overlapping to make it fit, then repeat with more sauce and another layer of pasta. Repeat with a further 2 layers of sauce and pasta, finishing with a layer of pasta.\nPut the crème fraîche in a bowl and mix with 2 tbsp water to loosen it and make a smooth pourable sauce. Pour this over the top of the pasta, then top with the mozzarella. Sprinkle Parmesan over the top and bake for 25–30 mins until golden and bubbling. Serve scattered with basil, if you like.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://www.bbcgoodfood.com/recipes/classic-lasagne",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52777",
    "title": "Mediterranean Pasta Salad",
    "description": "An Italian seafood from TheMealDB.",
    "category": "Seafood",
    "tags": [
      "italian",
      "pasta",
      "baking"
    ],
    "ingredients": "200 g mozzarella balls\n250 g baby plum tomatoes\n1  bunch fresh basil\n350 g farfalle\n3  tablespoons extra virgin olive oil\n40 g Green Olives\n200 g tuna\nto taste salt\nto taste pepper",
    "instructions": "Bring a large saucepan of salted water to the boil\nAdd the pasta, stir once and cook for about 10 minutes or as directed on the packet.\nMeanwhile, wash the tomatoes and cut into quarters. Slice the olives. Wash the basil.\nPut the tomatoes into a salad bowl and tear the basil leaves over them. Add a tablespoon of olive oil and mix.\nWhen the pasta is ready, drain into a colander and run cold water over it to cool it quickly.\nToss the pasta into the salad bowl with the tomatoes and basil.\nAdd the sliced olives, drained mozzarella balls, and chunks of tuna. Mix well and let the salad rest for at least half an hour to allow the flavours to mingle.\nSprinkle the pasta with a generous grind of black pepper and drizzle with the remaining olive oil just before serving.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://thelemonsqueezy.com/recipe/mediterranean-pasta-salad/",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52810",
    "title": "Osso Buco alla Milanese",
    "description": "An Italian miscellaneous from TheMealDB.",
    "category": "Miscellaneous",
    "tags": [
      "italian"
    ],
    "ingredients": "4 meaty shanks Veal\n½ cup Flour\n2 tablespoons Olive Oil\n3 tablespoons Butter\n1 medium chopped into ½-inch pieces Onion\n1 chopped into ½-inch pieces Carrots\n1 chopped into ½-inch pieces Celery\n1 bulb chopped into ½-inch pieces Fennel\n3 cloves Garlic\n2 strips Orange Zest\n1 ½ teaspoons Marjoram\n1 Bay Leaf\n1 cup Dry White Wine\n½ cup Chicken Stock\n1 cup chopped with juice Tomatoes\n2 tablespoons chopped Parsley\n1 teaspoon minced Garlic\n1 teaspoon grated Lemon Zest",
    "instructions": "Heat the oven to 300 degrees.\nDredging the shanks: pour the flour into a shallow dish (a pie plate works nicely). Season the veal shanks on all sides with salt and pepper. One at a time, roll the shanks around in the flour coat, and shake and pat the shank to remove any excuses flour. Discard the remaining flour.\nBrowning the shanks: put the oil and 1 tablespoon of the butter in a wide Dutch oven or heavy braising pot (6 to 7 quart) and heat over medium-high heat. When the butter has melted and the oil is shimmering, lower the shanks into the pot, flat side down; if the shanks won’t fit without touching one another, do this in batches. Brown the shanks, turning once with tongs, until both flat sides are well caramelized, about 5 minutes per side. If the butter-oil mixture starts to burn, lower the heat just a bit. Transfer the shanks to a large platter or tray and set aside.\nThe aromatics: pour off and discard the fat from the pot. Wipe out any burnt bits with a damp paper towel, being careful not to remove any delicious little caramelized bits. Ad the remaining 2 tablespoons butter to the pot and melt it over medium heat. When the butter has stopped foaming, add the onion, carrot, celery, and fennel. Season with salt and pepper, stir, and cook the vegetables until they begin to soften but do not brown, about 6 minutes. Stir in the garlic, orange zest, marjoram, and bay leaf, and stew for another minute or two.\nThe braising liquid: add the wine, increase the heat to high, and bring to a boil. Boil, stirring occasionally, to reduce the wine by about half, 5 minutes. Add the stock and tomatoes, with their juice, and boil again to reduce the liquid to about 1 cup total, about 10 minutes.\nThe braise: Place the shanks in the pot so that they are sitting with the exposed bone facing up, and pour over any juices that accumulated as they sat. Cover with parchment paper, pressing down so the parchment nearly touches the veal and the edges hang over the sides of the pot by about an inch. Cover tightly with the lid, and slide into the lower part of the oven to braise at a gentle simmer. Check the pot after the first 15 minutes, and if the liquid is simmering too aggressively, lower the oven heat by 10 or 15 degrees. Continue braising, turning the shanks and spooning some pan juices over the top after the first 40 minutes, until the meat is completely tender and pulling away from the bone, about 2 hours.\nThe gremolata: While the shanks are braising, stir together the garlic, parsley, and lemon zest in a small bowl. Cover with plastic wrap and set aside in a cool place (or the refrigerator, if your kitchen is very warm.)\nThe finish: When the veal is fork-tender and falling away from the bone, remove the lid and sprinkle over half of the gremolata. Return the veal to the oven, uncovered, for another 15 minutes to caramelize it some.\nUsing a slotted spatula or spoon, carefully lift the shanks from the braising liquid, doing your best to keep them intact. The shanks will be very tender and threatening to fall into pieces, and the marrow will be wobbly inside the bones, so this can be a bit tricky. But if they do break apart, don’t worry, the flavor won’t suffer at all. Arrange the shanks on a serving platter or other large plate, without stacking, and cover with foil to keep warm.\nFinishing the sauce: Set the braising pot on top of the stove and evaluate the sauce: if there is a visible layer of fat floating on the surface, use a large spoon to skim it off and discard it. Taste the sauce for concentration of flavor. If it tastes a bit weak or flat, bring it to a boil over high heat, and boil to reduce the volume and intensify the flavor for 5 to 10 minutes. Taste again for salt and pepper. If the sauce wants more zip, stir in a teaspoon or two of the remaining gremolata.\nPortioning the veal shanks: if the shanks are reasonably sized, serve one per person. If the shanks are gargantuan or you’re dealing with modest appetites, pull apart the larger shanks, separating them at their natural seams, and serve smaller amounts. Be sure to give the marrow bones to whomever prizes them most.\nServing: Arrange the veal shanks on warm dinner plates accompanied by the risotto, if serving. Just before carrying the plates to the table, sprinkle on the remaining gremolata and then spoon over a generous amount of sauce – the contact with the hot liquid will aromatize the gremolata and perk up everyone’s appetite with the whiff of garlic and lemon.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/wwuqvt1487345467.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://www.cookstr.com/Meat/Osso-Buco-alla-Milanese",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52837",
    "title": "Pilchard puttanesca",
    "description": "An Italian pasta from TheMealDB.",
    "category": "Pasta",
    "tags": [
      "italian"
    ],
    "ingredients": "300g Spaghetti\n1 tbls Olive Oil\n1 finely chopped Onion\n2 cloves minced Garlic\n1 Red Chilli\n1 tbls Tomato Puree\n425g Pilchards\n70g Black Olives\nShaved Parmesan",
    "instructions": "Cook the pasta following pack instructions. Heat the oil in a non-stick frying pan and cook the onion, garlic and chilli for 3-4 mins to soften. Stir in the tomato purée and cook for 1 min, then add the pilchards with their sauce. Cook, breaking up the fish with a wooden spoon, then add the olives and continue to cook for a few more mins.\nDrain the pasta and add to the pan with 2-3 tbsp of the cooking water. Toss everything together well, then divide between plates and serve, scattered with Parmesan.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/vvtvtr1511180578.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://www.bbcgoodfood.com/recipes/pilchard-puttanesca",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-53014",
    "title": "Pizza Express Margherita",
    "description": "An Italian miscellaneous from TheMealDB.",
    "category": "Miscellaneous",
    "tags": [
      "italian"
    ],
    "ingredients": "150ml Water\n1 tsp Sugar\n15g Yeast\n225g Plain Flour\n1 1/2 tsp Salt\nDrizzle Olive Oil\n80g Passata\n70g Mozzarella\nPeeled and Sliced Oregano\nLeaves Basil\nPinch Black Pepper",
    "instructions": "1 Preheat the oven to 230°C.\n2 Add the sugar and crumble the fresh yeast into warm water.\n3 Allow the mixture to stand for 10 – 15 minutes in a warm place (we find a windowsill on a sunny day works best) until froth develops on the surface.\n4 Sift the flour and salt into a large mixing bowl, make a well in the middle and pour in the yeast mixture and olive oil.\n5 Lightly flour your hands, and slowly mix the ingredients together until they bind.\n6 Generously dust your surface with flour.\n7 Throw down the dough and begin kneading for 10 minutes until smooth, silky and soft.\n8 Place in a lightly oiled, non-stick baking tray (we use a round one, but any shape will do!)\n9 Spread the passata on top making sure you go to the edge.\n10 Evenly place the mozzarella (or other cheese) on top, season with the oregano and black pepper, then drizzle with a little olive oil.\n11 Cook in the oven for 10 – 12 minutes until the cheese slightly colours.\n12 When ready, place the basil leaf on top and tuck in!",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://www.dailymail.co.uk/femail/food/article-8240361/Pizza-Express-release-secret-recipe-Margherita-Pizza-make-home.html",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52780",
    "title": "Potato Gratin with Chicken",
    "description": "An Italian chicken from TheMealDB.",
    "category": "Chicken",
    "tags": [
      "italian"
    ],
    "ingredients": "800g Potatoes\n3 Onions\n2 tblsp Olive Oil\n100ml Chicken Stock\n1 pot Creme Fraiche\nTopping Parmesan\n4 Chicken Breasts\n4 Bacon\nTopping Spinach\nTopping Peas",
    "instructions": "15 minute potato gratin with chicken and bacon greens: a gratin always seems more effort and more indulgent than ordinary boiled or roasts, but it doesn't have to take 45mins, it's nice for a change and you can control the calorie content by going with full fat to low fat creme fraiche. (It's always tastes better full fat though obviously!) to serve 4: use 800g of potatoes, finely slice and boil in a pan for about 5-8 mins till firmish, not soft. Finely slice 3 onions and place in an oven dish with 2 tblsp of olive oil and 100ml of chicken stock. Cook till the onions are soft then drain the potatoes and pour onto the onions. Season and spoon over cream or creme fraiche till all is covered but not swimming. Grate Parmesan over the top then finish under the grill till nicely golden. serve with chicken and bacon, peas and spinach.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/qwrtut1468418027.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://www.instagram.com/p/BHxR7hYBJ6P",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52811",
    "title": "Ribollita",
    "description": "An Italian vegetarian from TheMealDB.",
    "category": "Vegetarian",
    "tags": [
      "italian",
      "vegetarian"
    ],
    "ingredients": "5 tablespoons Olive Oil\n1 chopped Onion\n1 chopped Carrots\n1 stalk chopped Celery\n1 tablespoon minced Garlic\n2 cups Cannellini Beans\n1 Canned tomatoes\n4 cups Water\n1 fresh sprig Rosemary\n1 fresh sprig Thyme\n1 pound chopped Kale\n4 thick slices Wholegrain Bread\n1 thinly sliced Red Onions\n½ cup freshly grated Parmesan",
    "instructions": "Put 2 tablespoons of the oil in a large pot over medium heat. When it’s hot, add onion, carrot, celery and garlic; sprinkle with salt and pepper and cook, stirring occasionally, until vegetables are soft, 5 to 10 minutes.\nHeat the oven to 500 degrees. Drain the beans; if they’re canned, rinse them as well. Add them to the pot along with tomatoes and their juices and stock, rosemary and thyme. Bring to a boil, then reduce heat so the soup bubbles steadily; cover and cook, stirring once or twice to break up the tomatoes, until the flavors meld, 15 to 20 minutes.\nFish out and discard rosemary and thyme stems, if you like, and stir in kale. Taste and adjust seasoning. Lay bread slices on top of the stew so they cover the top and overlap as little as possible. Scatter red onion slices over the top, drizzle with the remaining 3 tablespoons oil and sprinkle with Parmesan.\nPut the pot in the oven and bake until the bread, onions and cheese are browned and crisp, 10 to 15 minutes. (If your pot fits under the broiler, you can also brown the top there.) Divide the soup and bread among 4 bowls and serve.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/xrrwpx1487347049.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://cooking.nytimes.com/recipes/1016052-ribollita",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52783",
    "title": "Rigatoni with fennel sausage sauce",
    "description": "An Italian lamb from TheMealDB.",
    "category": "Lamb",
    "tags": [
      "italian",
      "pasta"
    ],
    "ingredients": "2½ tbsp olive oil\n6 cut into 1.5cm-thick slices Italian fennel sausages\n1 large peeled and chopped onion\n1 trimmed and roughly chopped; reserve any fronds to garnish fennel bulb\n½ tsp smoky paprika\n1 clove, peeled and sliced garlic\n2 tsp lightly toasted and then gently crushed fennel seeds\n100ml red wine\n400g tinned chopped tomatoes\n½ tsp caster sugar\n50g cut in half lengthways pitted black olives\n500g rigatoni\n30g roughly crumbled into 0.5cm pieces pecorino\n1  rinsed and patted dry anchovy fillet\n1 clove, peeled and crushed garlic\n60ml olive oil\n50g torn basil leaves",
    "instructions": "Heat a tablespoon of oil in a large saute pan for which you have a lid. Add the sausage pieces and fry on a medium-high heat for 10 minutes, stirring regularly, until golden-brown all over. Transfer the sausages to a plate, then add the onion and fennel to the hot pan and fry for 15 minutes, stirring once in a while, until soft and caramelised; if the pan goes a bit dry, add a teaspoon or so of extra oil. Stir in the paprika, garlic and half the fennel seeds, fry for two minutes more, then pour on the wine and boil for 30 seconds, to reduce by half. Add the tomatoes, sugar, 100ml water, the seared sausage and half a teaspoon of salt, cover and simmer for 30 minutes; remove the lid after 10 minutes, and cook until the sauce is thick and rich. Remove from the heat, stir through the olives and remaining fennel seeds and set aside until you’re ready to serve.\nBring a large pot of salted water to a boil, add the pasta and cook for 12-14 minutes (or according to the instructions on the packet), until al dente. Meanwhile, reheat the sauce. Drain the pasta, return it to the pot, stir in a tablespoon of oil, then divide between the bowls.\nPut all the pesto ingredients except the basil in the small bowl of a food processor. Add a tablespoon of water and blitz to a rough paste. Add the basil, then blitz until just combined (the pesto has a much better texture if the basil is not overblended).\nSpoon over the ragù and top with a spoonful of pesto. Finish with a sprinkling of chopped fennel fronds, if you have any, and serve at once.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/qtqvys1468573168.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "http://www.ottolenghi.co.uk/recipes/meat/rigatoni-with-fennel-sausage-sauce-and-pecorino-and-anchovy-pesto-shop",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52823",
    "title": "Salmon Prawn Risotto",
    "description": "An Italian seafood from TheMealDB.",
    "category": "Seafood",
    "tags": [
      "italian",
      "fish"
    ],
    "ingredients": "50g/2oz butter\n1 finely chopped onion\n150g rice\n125ml white wine\n1 litre hot vegetable stock\nThe juice and zest of one lemon\n240g large King Prawns\n150g salmon\n100g tips blanched briefly in boiling water asparagus\nground black pepper\n50g shavings Parmesan",
    "instructions": "Melt the butter in a thick-based pan and gently cook the onion without colour until it is soft.\nAdd the rice and stir to coat all the grains in the butter\nAdd the wine and cook gently stirring until it is absorbed\nGradually add the hot stock, stirring until each addition is absorbed. Keep stirring until the rice is tender\nSeason with the lemon juice and zest, and pepper to taste. (there will probably be sufficient saltiness from the salmon to not need to add salt) Stir gently to heat through\nServe scattered with the Parmesan and seasonal vegetables.\nGrill the salmon and gently place onto the risotto with the prawns and asparagus",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/xxrxux1503070723.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "http://www.rangemaster.co.uk/rangemaster-owners/recipes-ideas-inspiration/recipes/mains/prawn-and-hot-smoked-salmon-risotto-with-asparagus",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52982",
    "title": "Spaghetti alla Carbonara",
    "description": "An Italian pasta from TheMealDB.",
    "category": "Pasta",
    "tags": [
      "italian",
      "pasta",
      "bbq",
      "breakfast"
    ],
    "ingredients": "320g Spaghetti\n6 Egg Yolks\nAs required Salt\n150g Bacon\n50g Pecorino\nAs required Black Pepper",
    "instructions": "STEP 1\nPut a large saucepan of water on to boil.\nSTEP 2\nFinely chop the 100g pancetta, having first removed any rind. Finely grate 50g pecorino cheese and 50g parmesan and mix them together.\nSTEP 3\nBeat the 3 large eggs in a medium bowl and season with a little freshly grated black pepper. Set everything aside.\nSTEP 4\nAdd 1 tsp salt to the boiling water, add 350g spaghetti and when the water comes back to the boil, cook at a constant simmer, covered, for 10 minutes or until al dente (just cooked).\nSTEP 5\nSquash 2 peeled plump garlic cloves with the blade of a knife, just to bruise it.\nSTEP 6\nWhile the spaghetti is cooking, fry the pancetta with the garlic. Drop 50g unsalted butter into a large frying pan or wok and, as soon as the butter has melted, tip in the pancetta and garlic.\nSTEP 7\nLeave to cook on a medium heat for about 5 minutes, stirring often, until the pancetta is golden and crisp. The garlic has now imparted its flavour, so take it out with a slotted spoon and discard.\nSTEP 8\nKeep the heat under the pancetta on low. When the pasta is ready, lift it from the water with a pasta fork or tongs and put it in the frying pan with the pancetta. Don’t worry if a little water drops in the pan as well (you want this to happen) and don’t throw the pasta water away yet.\nSTEP 9\nMix most of the cheese in with the eggs, keeping a small handful back for sprinkling over later.\nSTEP 10\nTake the pan of spaghetti and pancetta off the heat. Now quickly pour in the eggs and cheese. Using the tongs or a long fork, lift up the spaghetti so it mixes easily with the egg mixture, which thickens but doesn’t scramble, and everything is coated.\nSTEP 11\nAdd extra pasta cooking water to keep it saucy (several tablespoons should do it). You don’t want it wet, just moist. Season with a little salt, if needed.\nSTEP 12\nUse a long-pronged fork to twist the pasta on to the serving plate or bowl. Serve immediately with a little sprinkling of the remaining cheese and a grating of black pepper. If the dish does get a little dry before serving, splash in some more hot pasta water and the glossy sauciness will be revived.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://www.bbcgoodfood.com/recipes/ultimate-spaghetti-carbonara-recipe",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52770",
    "title": "Spaghetti Bolognese",
    "description": "An Italian beef from TheMealDB.",
    "category": "Beef",
    "tags": [
      "italian",
      "pasta",
      "meat"
    ],
    "ingredients": "2 onions\n1tbsp olive oil\n1 clove garlic\n500g lean minced beef\n90g mushrooms\n1tsp dried oregano\n400g can tomatoes\n300ml hot beef stock\n1tbsp tomato puree\n1tbsp worcestershire sauce\n350g spaghetti\nTopping parmesan",
    "instructions": "Put the onion and oil in a large pan and fry over a fairly high heat for 3-4 mins. Add the garlic and mince and fry until they both brown. Add the mushrooms and herbs, and cook for another couple of mins.\nStir in the tomatoes, beef stock, tomato ketchup or purée, Worcestershire sauce and seasoning. Bring to the boil, then reduce the heat, cover and simmer, stirring occasionally, for 30 mins.\nMeanwhile, cook the spaghetti in a large pan of boiling, salted water, according to packet instructions. Drain well, run hot water through it, put it back in the pan and add a dash of olive oil, if you like, then stir in the meat sauce. Serve in hot bowls and hand round Parmesan cheese, for sprinkling on top.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://www.themealdb.com/meal/52770",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52771",
    "title": "Spicy Arrabiata Penne",
    "description": "An Italian vegetarian from TheMealDB.",
    "category": "Vegetarian",
    "tags": [
      "italian",
      "pasta",
      "curry"
    ],
    "ingredients": "1 pound penne rigate\n1/4 cup olive oil\n3 cloves garlic\n1 tin chopped tomatoes\n1/2 teaspoon red chilli flakes\n1/2 teaspoon italian seasoning\n6 leaves basil\nsprinkling Parmigiano-Reggiano",
    "instructions": "Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://www.themealdb.com/meal/52771",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52849",
    "title": "Spinach & Ricotta Cannelloni",
    "description": "An Italian vegetarian from TheMealDB.",
    "category": "Vegetarian",
    "tags": [
      "italian"
    ],
    "ingredients": "3 tbsp Olive Oil\n8 cloves chopped Garlic\n3 tbsp Caster Sugar\n2 tblsp Red Wine Vinegar\n3 400g Cans Chopped Tomatoes\nBunch Basil Leaves\n2 tubs Mascarpone\n3 tbsp Milk\n85g Parmesan\n2 sliced Mozzarella\n1kg Spinach\n100g Parmesan\n3 tubs Ricotta\npinch Nutmeg\n400g Cannellini Beans",
    "instructions": "First make the tomato sauce. Heat the oil in a large pan and fry the garlic for 1 min. Add the sugar, vinegar, tomatoes and some seasoning and simmer for 20 mins, stirring occasionally, until thick. Add the basil and divide the sauce between 2 or more shallow ovenproof dishes (see Tips for freezing, below). Set aside. Make a sauce by beating the mascarpone with the milk until smooth, season, then set aside.\nPut the spinach in a large colander and pour over a kettle of boiling water to wilt it (you may need to do this in batches). When cool enough to handle squeeze out the excess water. Roughly chop the spinach and mix in a large bowl with 100g Parmesan and ricotta. Season well with salt, pepper and the nutmeg.\nHeat oven to 200C/180C fan/gas 6. Using a piping bag or plastic food bag with the corner snipped off, squeeze the filling into the cannelloni tubes. Lay the tubes, side by side, on top of the tomato sauce and spoon over the mascarpone sauce. Top with Parmesan and mozzarella. You can now freeze the cannelloni, uncooked, or you can cook it first and then freeze. Bake for 30-35 mins until golden and bubbling. Remove from oven and let stand for 5 mins before serving.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/wspuvp1511303478.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://www.bbcgoodfood.com/recipes/531632/spinach-and-ricotta-cannelloni",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52866",
    "title": "Squash linguine",
    "description": "An Italian vegetarian from TheMealDB.",
    "category": "Vegetarian",
    "tags": [
      "italian",
      "pasta",
      "light"
    ],
    "ingredients": "350g Butternut Squash\n3 parts Garlic\n3 tbs Olive Oil\n350g Linguine Pasta\nSmall bunch Sage",
    "instructions": "Heat oven to 200C/180C fan/gas 6. Put the squash and garlic on a baking tray and drizzle with the olive oil. Roast for 35-40 mins until soft. Season.\nCook the pasta according to pack instructions. Drain, reserving the water. Use a stick blender to whizz the squash with 400ml cooking water. Heat some oil in a frying pan, fry the sage until crisp, then drain on kitchen paper. Tip the pasta and sauce into the pan and warm through. Scatter with sage.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/wxswxy1511452625.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://www.bbcgoodfood.com/recipes/creamy-squash-linguine",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  },
  {
    "id": "themealdb-52775",
    "title": "Vegan Lasagna",
    "description": "An Italian vegan from TheMealDB.",
    "category": "Vegan",
    "tags": [
      "italian",
      "vegan",
      "pasta"
    ],
    "ingredients": "1 cups green red lentils\n1 Carrots\n1 onion\n1 small zucchini\nsprinking coriander\n150g spinach\n10 lasagne sheets\n35g vegan butter\n4 tablespoons flour\n300ml soya milk\n1.5 teaspoons mustard\n1 teaspoon vinegar",
    "instructions": "1) Preheat oven to 180 degrees celcius.\n2) Boil vegetables for 5-7 minutes, until soft. Add lentils and bring to a gentle simmer, adding a stock cube if desired. Continue cooking and stirring until the lentils are soft, which should take about 20 minutes.\n3) Blanch spinach leaves for a few minutes in a pan, before removing and setting aside.\n4) Top up the pan with water and cook the lasagne sheets. When cooked, drain and set aside.\n5) To make the sauce, melt the butter and add the flour, then gradually add the soya milk along with the mustard and the vinegar. Cook and stir until smooth and then assemble the lasagne as desired in a baking dish.\n6) Bake in the preheated oven for about 25 minutes.",
    "prepTime": "",
    "cookTime": "",
    "servings": "",
    "notes": "Imported from TheMealDB. Adjust notes, times, and servings to match your kitchen.",
    "rating": 0,
    "image": "https://www.themealdb.com/images/media/meals/rvxxuy1468312893.jpg",
    "sourceName": "TheMealDB",
    "sourceUrl": "https://www.themealdb.com/meal/52775",
    "createdAt": "2026-05-19T22:50:49.708Z",
    "updatedAt": "2026-05-19T22:50:49.708Z"
  }
]
